---
title: "R Notebook"
output: 
---

```{r}
taxa <- read.csv('../DATA/human_16S.even13190.rel.sig.csv', row.names = 1)
taxa <- t(taxa)

meta <- read.csv('../METADATA/human_16S.sampleinfo.csv', sep = ',', row.names = 1)
# rownames(meta) <- meta$Sample

```

```{r}
rare.depth = 13190
otu = log10(round(taxa * rare.depth) + 1)

data.plot = scale((as.matrix(otu)), scale=FALSE)

```

```{r, fig.height=10}
cols_of_interest <- c("Response", "BORR")
meta_subset <- meta[,colnames(meta) %in% cols_of_interest]
meta_for_heatmap = meta_subset[order(meta_subset$Response),]

annotation_colors = list(Response = c('NonResponder' ='red', 'Responder'="green"))

# count_matrix_for_clustering[match(rownames(meta_for_heatmap.ordered), rownames(count_matrix_for_clustering)),]


ordered_counts <- taxa[match(rownames(meta_for_heatmap), rownames(taxa)),]

pheatmap(log(ordered_counts+0.0001), 
         annotation_row = meta_for_heatmap,
                   # annotation_colors = annotation_colors,

         cluster_rows = T,
         cluster_cols = T,
         show_rownames = F
         )

pheatmap(log(taxa+0.0001))
pheatmap(log10(round(taxa * rare.depth) + 1), annotation_row = meta_for_heatmap, annotation_colors = annotation_colors,)


```


```{r}
taxa <- otu
# taxa_paper_zer <- taxa[,apply(taxa,2,function(col) {sum(col==0)<35})]
taxa.mds <- metaMDS(comm = taxa, distance = "binomial", trace = FALSE, autotransform = FALSE)
taxa.mds$stress

MDS_xy <- data.frame(taxa.mds$points)
MDS_xy$Response <- meta$Response
ggplot(MDS_xy, aes(MDS1, MDS2, color = Response)) + geom_point() + theme_bw()
```