---
title: "R Notebook"
output: 
---
```{r}
library(pheatmap)
library(factoextra)
library(labdsv)

library(ade4)
library(vegan)
library(gclus)
library(ape)
library(FactoMineR)
```


```{r}
taxa <- read.csv('../DATA/mp2_human_wgs_mp2_genus.tsv', sep = '\t', row.names = 1)
meta <- read.csv('../METADATA/meta_human_wgs.tsv', sep = '\t', row.names = 1)

```

```{r, fig.width=10, fig.height=14}
# library(tidyverse)


count_matrix_for_clustering <- as.data.frame(taxa[order(rownames(taxa)), ])

count_matrix_for_clustering <- count_matrix_for_clustering[,colMeans(count_matrix_for_clustering) > 0.001]
count_matrix_for_clustering <- log(count_matrix_for_clustering +0.0001)

cols_of_interest <- c("Response", "BORR")
meta_subset <- meta[,colnames(meta) %in% cols_of_interest]

# clustering itself
set.seed(42)
km <- kmeans(count_matrix_for_clustering, 5, nstart = 25)

# prepare annoation dataframe
meta_for_heatmap <- meta_subset
meta_for_heatmap <- cbind(meta_for_heatmap, clusterNum = as.factor(km$cluster))

# # Prepare annotation colors
# annotation_colors = list(`Лучший.ответ.по.критериям.irRECIST` = c('Полный ответ' ='green', 'Прогрессирование'="red", 'Стабилизация'='yellow', 'Частичный ответ' = 'blue'))


meta_for_heatmap.ordered = meta_for_heatmap[order(meta_for_heatmap$Response),]

# meta_for_heatmap.ordered <- meta_for_heatmap.ordered[,colnames(meta_for_heatmap.ordered) %in% c("Response", 'clusterNum')]

# Sort original data frame by the order of the new data frame
count_matrix_for_clustering[match(rownames(meta_for_heatmap.ordered), rownames(count_matrix_for_clustering)),]


ordered_counts <- count_matrix_for_clustering[match(rownames(meta_for_heatmap.ordered), rownames(count_matrix_for_clustering)),]

pheatmap(ordered_counts, 
         annotation_row = meta_for_heatmap.ordered,
                   # annotation_colors = annotation_colors,

         cluster_rows = F,
         cluster_cols = T,
         show_rownames = F
         )
```


```{r}
taxa_paper <- read.csv('../DATA/human_shotgun.rel.full.csv', row.names = 1)
taxa_paper <- t(taxa_paper)
pmeta <- meta
rownames(pmeta) <- pmeta$Sample
```

```{r}
taxa_paper_zer <- taxa_paper[,apply(taxa_paper,2,function(col) {sum(col==0)<35})]
taxa.mds <- metaMDS(comm = taxa_paper_zer, distance = "bray", trace = FALSE, autotransform = FALSE)
taxa.mds$stress

MDS_xy <- data.frame(taxa.mds$points)
MDS_xy$Response <- pmeta$Response
ggplot(MDS_xy, aes(MDS1, MDS2, color = Response)) + geom_point() + theme_bw()
```


```{r}
taxa.mds <- metaMDS(comm = taxa, distance = "bray", trace = FALSE, autotransform = FALSE)
taxa.mds$stress

MDS_xy <- data.frame(taxa.mds$points)
MDS_xy$Response <- meta$Response
ggplot(MDS_xy, aes(MDS1, MDS2, color = Response)) + geom_point() + theme_bw()
```









```{r}
res.pca <- prcomp(count_matrix_for_clustering, scale = TRUE)
fviz_eig(res.pca)

```



```{r}
fviz_pca_ind(res.pca,
             col.ind = "cos2", # Color by the quality of representation
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
             )
```

```{r, fig.width=20, fig.height=20}
fviz_pca_var(res.pca,
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
             )
```


```{r, fig.width=10, fig.height=10}
groups <- as.factor(meta$Response)
fviz_pca_ind(res.pca,
             col.ind = groups, # color by groups
             palette = c("#00AFBB",  "#FC4E07"),
             addEllipses = TRUE, # Concentration ellipses
             ellipse.type = "confidence",
             legend.title = "Groups",
             repel = TRUE
             )
```


```{r, fig.width=20, fig.height=20}

dis.bray <- vegdist(taxa, method="bray")
bray.pco <- pco(dis.bray,k=10)
barplot(bray.pco$eig)
plot(bray.pco)
groups <- as.factor(meta$Response)
fviz_pca_ind(bray.pco,
             col.ind = groups, # color by groups
             palette = c("#00AFBB",  "#FC4E07"),
             addEllipses = TRUE, # Concentration ellipses
             ellipse.type = "confidence",
             legend.title = "Groups",
             repel = TRUE
             )
```


